version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app/
    entrypoint: ./entrypoint.sh
    
    depends_on:
      - database
  
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432